#!/usr/bin/env python3
"""Generate bulk seed SQL for DDMA load testing.

Mirrors PasswordHashService: sha256$<salt_hex>$<sha256hex(salt:raw)>

Usage:
    python3 gen_seed.py                       # writes loadtest_seed.sql next to this script
    python3 gen_seed.py --vehicles-per-bucket 8000 --out extra_vehicles.sql --users 0

Load the result into a running Postgres with:
    docker exec -i <db-container> psql -U postgres -d ddma < loadtest_seed.sql
"""
import argparse
import hashlib
import secrets
import uuid
from pathlib import Path

PASSWORD = "LoadTest123!"

# Fixed IDs from backend/DeliveryManagement/src/main/resources/database-init.sql
CENTERS = [
    "c0000003-0000-0000-0000-000000000001",  # SoMa Hub
    "c0000003-0000-0000-0000-000000000002",  # Mission Hub
    "c0000003-0000-0000-0000-000000000003",  # Castro Hub
]
VEHICLE_TYPES = ("DRONE", "ROBOT")


def hash_password(raw: str) -> str:
    salt = secrets.token_hex(12)
    digest = hashlib.sha256(f"{salt}:{raw}".encode()).hexdigest()
    return f"sha256${salt}${digest}"


def esc(s: str) -> str:
    return s.replace("'", "''")


def gen_users(n: int) -> list[str]:
    rows = []
    for i in range(1, n + 1):
        uid = str(uuid.uuid4())
        email = f"loadtest_user_{i:05d}@example.com"
        phone = f"+1415555{i:05d}"[:15]
        pwd_hash = hash_password(PASSWORD)
        full_name = f"Load Test User {i}"
        rows.append(
            f"('{uid}', '{esc(email)}', '{esc(phone)}', '{pwd_hash}', '{esc(full_name)}', FALSE)"
        )
    return rows


def gen_vehicles(per_bucket: int, tag: str) -> list[str]:
    rows = []
    counter = 1
    for center_id in CENTERS:
        for vtype in VEHICLE_TYPES:
            for _ in range(per_bucket):
                vid = str(uuid.uuid4())
                dev = f"{tag}-{vtype}-{counter:06d}"
                rows.append(f"('{vid}', '{center_id}', '{vtype}', TRUE, '{dev}')")
                counter += 1
    return rows


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--users", type=int, default=2000, help="number of load-test users to generate (0 to skip)")
    parser.add_argument("--vehicles-per-bucket", type=int, default=500,
                         help="vehicles per (center, vehicle_type) combination, i.e. per bucket (0 to skip). "
                              "500 = realistic fleet scale used for the baseline/fixed-comparison runs. "
                              "8000 = the inflated scale used to surface the over-fetch bug.")
    parser.add_argument("--tag", default="LOADTEST", help="external_device_id prefix, keep unique per invocation "
                                                            "if you run this multiple times against the same DB")
    parser.add_argument("--out", default=None, help="output SQL file (default: loadtest_seed.sql next to this script)")
    args = parser.parse_args()

    out_path = Path(args.out) if args.out else Path(__file__).parent / "loadtest_seed.sql"

    out = ["-- Bulk load-test seed data. Generated by gen_seed.py.",
           "-- Not part of the app's core schema/seed (database-init.sql) — apply separately to a test DB.",
           "BEGIN;"]

    if args.users > 0:
        out.append("INSERT INTO app_user (id, email, phone, password_hash, full_name, guest) VALUES")
        out.append(",\n".join(gen_users(args.users)) + ";")

    if args.vehicles_per_bucket > 0:
        vehicle_rows = gen_vehicles(args.vehicles_per_bucket, args.tag)
        out.append("INSERT INTO fleet_vehicle (id, center_id, vehicle_type, available, external_device_id) VALUES")
        out.append(",\n".join(vehicle_rows) + ";")
    else:
        vehicle_rows = []

    out.append("COMMIT;")

    out_path.write_text("\n".join(out))

    print(f"Wrote {out_path}")
    print(f"  users:    {args.users} (login password for all: {PASSWORD})")
    print(f"  vehicles: {len(vehicle_rows)} ({args.vehicles_per_bucket} per center/type bucket)")


if __name__ == "__main__":
    main()
